import type { Product, Category, Review } from './types';

export const categories: Category[] = [
  { id: 'cat1', name: 'Chairs' },
  { id: 'cat2', name: 'Desks' },
  { id: 'cat3', name: 'Sofas' },
  { id: 'cat4', name: 'Lamps' },
  { id: 'cat5', name: 'Tables' },
  { id: 'cat6', name: 'Decor' },
  { id: 'cat7', name: 'Storage' },
  { id: 'cat8', name: 'Rugs' },
];

const reviews: Review[] = [
  { id: 'rev1', author: 'Jane Doe', rating: 5, text: 'Absolutely love this chair! So comfortable and stylish.', date: '2023-05-10' },
  { id: 'rev2', author: 'John Smith', rating: 4, text: 'Great product, but assembly was a bit tricky.', date: '2023-04-22' },
];

export const products: Product[] = [
  {
    id: 'prod1',
    name: 'The Ergonomic Chair',
    slug: 'the-ergonomic-chair',
    description: 'A masterpiece of comfort and design. The Ergonomic Chair provides full-body support and a sleek aesthetic that fits any modern workspace.',
    price: 399.99,
    category: categories[0],
    images: [{ id: 'img1', url: 'https://picsum.photos/seed/chair1/600/600', alt: 'A sleek, modern chair' }],
    rating: 4.8,
    reviewCount: 120,
    stock: 25,
    reviews,
    featured: true,
  },
  {
    id: 'prod2',
    name: 'Minimalist Desk',
    slug: 'minimalist-desk',
    description: 'Crafted from solid oak, this minimalist desk offers a spacious and sturdy surface for all your creative and professional endeavors.',
    price: 549.00,
    category: categories[1],
    images: [{ id: 'img2', url: 'https://picsum.photos/seed/desk1/600/600', alt: 'A minimalist wooden desk' }],
    rating: 4.9,
    reviewCount: 85,
    stock: 15,
    reviews: [],
    featured: true,
  },
  {
    id: 'prod3',
    name: 'Cloud Sofa',
    slug: 'cloud-sofa',
    description: 'As comfortable as its name suggests, the Cloud Sofa is perfect for lounging. Its modular design adapts to any living space.',
    price: 1299.50,
    category: categories[2],
    images: [{ id: 'img3', url: 'https://picsum.photos/seed/sofa1/600/600', alt: 'A stylish sofa' }],
    rating: 4.7,
    reviewCount: 95,
    stock: 8,
    reviews,
    featured: true,
  },
  {
    id: 'prod4',
    name: 'Arc Floor Lamp',
    slug: 'arc-floor-lamp',
    description: 'Illuminate your space with the elegant Arc Floor Lamp. Its marble base and sweeping form make it a statement piece.',
    price: 249.00,
    category: categories[3],
    images: [{ id: 'img4', url: 'https://picsum.photos/seed/lamp1/600/600', alt: 'A contemporary floor lamp' }],
    rating: 4.6,
    reviewCount: 78,
    stock: 30,
    reviews: [],
    featured: true,
  },
  {
    id: 'prod5',
    name: 'Organic Coffee Table',
    slug: 'organic-coffee-table',
    description: 'A beautiful and functional centerpiece for your living room, with a unique, organic shape and smooth finish.',
    price: 450.00,
    category: categories[4],
    images: [{ id: 'img5', url: 'https://picsum.photos/seed/table1/600/600', alt: 'A modern coffee table' }],
    rating: 4.8,
    reviewCount: 60,
    stock: 18,
    reviews: [],
    featured: false,
  },
  {
    id: 'prod6',
    name: 'Ceramic Vase Trio',
    slug: 'ceramic-vase-trio',
    description: 'A set of three matte ceramic vases, perfect for adding a touch of minimalist elegance to any shelf or table.',
    price: 89.99,
    category: categories[5],
    images: [{ id: 'img6', url: 'https://picsum.photos/seed/vase1/600/600', alt: 'A decorative vase set' }],
    rating: 4.9,
    reviewCount: 150,
    stock: 50,
    reviews: [],
    featured: false,
  },
  {
    id: 'prod7',
    name: 'Ladder Bookshelf',
    slug: 'ladder-bookshelf',
    description: 'A modern and space-saving storage solution that leans against your wall, perfect for books, plants, and decor.',
    price: 180.00,
    category: categories[6],
    images: [{ id: 'img7', url: 'https://picsum.photos/seed/bookshelf1/600/600', alt: 'Bookshelf' }],
    rating: 4.7,
    reviewCount: 92,
    stock: 22,
    reviews: [],
    featured: false,
  },
  {
    id: 'prod8',
    name: 'Abstract Art Rug',
    slug: 'abstract-art-rug',
    description: 'Add a splash of color and personality to your room with this plush, non-shedding area rug featuring a vibrant abstract design.',
    price: 320.00,
    category: categories[7],
    images: [{ id: 'img8', url: 'https://picsum.photos/seed/rug1/600/600', alt: 'Area rug' }],
    rating: 4.8,
    reviewCount: 55,
    stock: 12,
    reviews: [],
    featured: false,
  },
];
