import type { Product, Category, Review } from './types';
import { subDays } from 'date-fns';

export const categories: Category[] = [
  { id: 'cat1', name: 'Veg' },
  { id: 'cat2', name: 'Chicken' },
  { id: 'cat3', name: 'Mutton' },
  { id: 'cat4', name: 'Egg' },
  { id: 'cat5', name: 'Fish' },
  { id
: 'cat6', name: 'Breads' },
  { id: 'cat7', name: 'Desserts' },
  { id: 'cat8', name: 'Beverages' },
];

const reviews: Review[] = [
  { id: 'rev1', author: 'Ishita M.', rating: 5, text: 'Absolutely delicious! The best biryani I have had in a long time.', date: '2023-05-10' },
  { id: 'rev2', author: 'Rohan S.', rating: 4, text: 'Great taste, but the portion size could be a bit bigger.', date: '2023-04-22' },
];

export const products: Product[] = [
  {
    id: 'prod1',
    name: 'Chicken Biryani',
    slug: 'chicken-biryani',
    description: 'Indulge in the legendary aroma of our Chicken Biryani. A culinary celebration by Bumba\'s Kitchen, this exquisite dish features succulent chicken pieces and aromatic \'Fortune\' style basmati rice, slow-cooked with a secret blend of spices. Each spoonful offers a harmonious blend of flavors, promising a regal meal that tantalizes your palate and leaves a memorable aftertaste.',
    price: 109,
    category: categories[1],
    images: [
      { id: 'img1a', url: 'https://picsum.photos/seed/biryani1/600/600', alt: 'Delicious Chicken Biryani' },
      { id: 'img1b', url: 'https://picsum.photos/seed/biryani2/600/600', alt: 'Close up of Chicken Biryani' },
      { id: 'img1c', url: 'https://picsum.photos/seed/biryani3/600/600', alt: 'Serving of Chicken Biryani' },
      { id: 'img1d', url: 'https://picsum.photos/seed/biryani4/600/600', alt: 'Chicken Biryani with raita' },
    ],
    rating: 4.6,
    reviewCount: 120,
    stock: 25,
    reviews,
    featured: true,
    createdAt: subDays(new Date(), 2).toISOString(),
  },
  {
    id: 'prod2',
    name: 'Veg Pulao',
    slug: 'veg-pulao',
    description: 'A fragrant and wholesome dish made with basmati rice, mixed vegetables, and a blend of aromatic spices. A perfect meal for any time of the day.',
    price: 89,
    category: categories[0],
    images: [
      { id: 'img2a', url: 'https://picsum.photos/seed/pulao1/600/600', alt: 'Veg Pulao' },
      { id: 'img2b', url: 'https://picsum.photos/seed/pulao2/600/600', alt: 'A bowl of veg pulao' }
    ],
    rating: 4.8,
    reviewCount: 85,
    stock: 15,
    reviews: [],
    featured: true,
    createdAt: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 'prod3',
    name: 'Mutton Korma',
    slug: 'mutton-korma',
    description: 'Tender mutton pieces cooked in a rich and creamy gravy, flavored with a blend of traditional Indian spices. A royal treat for your taste buds.',
    price: 159,
    category: categories[2],
    images: [{ id: 'img3', url: 'https://picsum.photos/seed/korma1/600/600', alt: 'Mutton Korma' }],
    rating: 4.7,
    reviewCount: 95,
    stock: 8,
    reviews,
    featured: true,
    createdAt: subDays(new Date(), 10).toISOString(),
  },
  {
    id: 'prod4',
    name: 'Egg Curry',
    slug: 'egg-curry',
    description: 'Boiled eggs simmered in a flavorful tomato-based gravy with a mix of Indian spices. A simple yet satisfying dish.',
    price: 79,
    category: categories[3],
    images: [{ id: 'img4', url: 'https://picsum.photos/seed/eggcurry1/600/600', alt: 'Egg Curry' }],
    rating: 4.5,
    reviewCount: 78,
    stock: 30,
    reviews: [],
    featured: true,
    createdAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'prod5',
    name: 'Fish Fry',
    slug: 'fish-fry',
    description: 'Fresh fish fillets marinated in a spicy blend and shallow-fried to golden perfection. Crispy on the outside, tender on the inside.',
    price: 129,
    category: categories[4],
    images: [{ id: 'img5', url: 'https://picsum.photos/seed/fishfry1/600/600', alt: 'Fish Fry' }],
    rating: 4.8,
    reviewCount: 60,
    stock: 18,
    reviews: [],
    featured: false,
     createdAt: subDays(new Date(), 15).toISOString(),
  },
  {
    id: 'prod6',
    name: 'Garlic Naan',
    slug: 'garlic-naan',
    description: 'Soft and fluffy Indian bread topped with finely chopped garlic and butter. The perfect accompaniment to any curry.',
    price: 25,
    category: categories[5],
    images: [{ id: 'img6', url: 'https://picsum.photos/seed/naan1/600/600', alt: 'Garlic Naan' }],
    rating: 4.9,
    reviewCount: 150,
    stock: 50,
    reviews: [],
    featured: false,
    createdAt: subDays(new Date(), 20).toISOString(),
  },
  {
    id: 'prod7',
    name: 'Gulab Jamun',
    slug: 'gulab-jamun',
    description: 'Soft, spongy balls made of milk solids, soaked in a light and sweet sugar syrup. A classic Indian dessert to complete your meal.',
    price: 49,
    category: categories[6],
    images: [{ id: 'img7', url: 'https://picsum.photos/seed/gulabjamun1/600/600', alt: 'Gulab Jamun' }],
    rating: 4.7,
    reviewCount: 92,
    stock: 22,
    reviews: [],
    featured: false,
    createdAt: subDays(new Date(), 3).toISOString(),
  },
  {
    id: 'prod8',
    name: 'Masala Chaas',
    slug: 'masala-chaas',
    description: 'A refreshing and digestive buttermilk drink, flavored with a mix of spices like cumin, ginger, and coriander.',
    price: 39,
    category: categories[7],
    images: [{ id: 'img8', url: 'https://picsum.photos/seed/chaas1/600/600', alt: 'Masala Chaas' }],
    rating: 4.8,
    reviewCount: 55,
    stock: 12,
    reviews: [],
    featured: false,
    createdAt: subDays(new Date(), 30).toISOString(),
  },
  {
    id: 'prod9',
    name: 'Chicken Kosha',
    slug: 'chicken-kosha',
    description: 'A semi-dry, rich and spicy Bengali chicken curry. Slow-cooked to perfection, allowing the chicken to absorb all the flavors.',
    price: 139,
    category: categories[1],
    images: [{ id: 'img9', url: 'https://picsum.photos/seed/kosha1/600/600', alt: 'Chicken Kosha' }],
    rating: 4.9,
    reviewCount: 150,
    stock: 20,
    reviews: [],
    featured: true,
    createdAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'prod10',
    name: 'Chicken Manchurian',
    slug: 'chicken-manchurian',
    description: 'An Indo-Chinese classic. Crispy chicken chunks tossed in a tangy and savory Manchurian sauce.',
    price: 119,
    category: categories[1],
    images: [{ id: 'img10', url: 'https://picsum.photos/seed/manchurian1/600/600', alt: 'Chicken Manchurian' }],
    rating: 4.7,
    reviewCount: 90,
    stock: 25,
    reviews: [],
    featured: false,
    createdAt: subDays(new Date(), 4).toISOString(),
  },
  {
    id: 'prod11',
    name: 'Kahi Chicken Curry',
    slug: 'kahi-chicken-curry',
    description: 'A rich and aromatic chicken curry cooked in a traditional Indian kadai with bell peppers and onions.',
    price: 200,
    category: categories[1],
    images: [{ id: 'img11', url: 'https://picsum.photos/seed/kadai1/600/600', alt: 'Kahi Chicken Curry' }],
    rating: 4.6,
    reviewCount: 80,
    stock: 18,
    reviews: [],
    featured: false,
    createdAt: subDays(new Date(), 8).toISOString(),
  },
  {
    id: 'prod12',
    name: 'Chilli Chicken',
    slug: 'chilli-chicken',
    description: 'A popular Indo-Chinese appetizer where crispy chicken is tossed in a spicy, sweet, and tangy sauce.',
    price: 259,
    category: categories[1],
    images: [{ id: 'img12', url: 'https://picsum.photos/seed/chilli1/600/600', alt: 'Chilli Chicken' }],
    rating: 4.8,
    reviewCount: 110,
    stock: 22,
    reviews: [],
    featured: true,
    createdAt: subDays(new Date(), 12).toISOString(),
  },
];
